### ISSUE TITLE
Does not support non-querystring pagination

### ISSUE THREAD

**Issue by Bilge** [s-damian/damian-pagination-php#1]
Correct me if I'm wrong, but it seems this library is making assumptions about how pagination should be propagated via the URL. Specifically, it assumes:

* The pagination parameters will be part of the query string.
* The query string keys are [hard-coded](https://github.com/s-damian/damian-pagination-php/blob/1dbfedcc984dd98ab8f9b69e34084f08f8bae680/src/DamianPaginationPhp/Pagination.php#L23-L25) to `page` and `pp`.

This obviously does not support URL pagination formats such as `http://example.com/my/page/123`.

**Comment by s-damian** [comment]
Hello.
Yes, for the moment this pagination only supports: ```?page=X``` and ```&pp=X```.
Thanks
